_target_: models.projector.inverse_dynamics.InverseDynamicsProjector
window_size: ${window_size}
input_dim: ${encoder.output_dim}
n_layer: 6
n_head: 6
n_embd: 120
# output_dim: for sim environments, set it to the state-based observation dimension.
# for real environments, set it to the estimated underlying environment state dimension.
# (e.g. if we have a 7DoF robot arm and a free rigid object, 16 should work fine)
output_dim: OUTPUT_DIM
dropout: 0.0
