defaults:
  - env_vars: env_vars
  - encoder: pusht_dynamo
  - _self_

seed: 42
window_size: 5
goal_window_size: 5
eval_window_size: 5

batch_size: 512
epochs: 5000
eval_freq: 10
eval_on_env_freq: 100
num_env_evals: 100
num_final_evals: 100
num_final_eval_per_goal: 1
action_window_size: 5

goal_dim: 0
wandb:
  project: dynamo-repro
  entity: ${env_vars.wandb_entity}
train_fraction: 0.9

device: cuda
optim:
  lr: 5.5e-5
  weight_decay: 2e-4
  betas: [0.9, 0.999]

env:
  gym:
    _target_: envs.pusht.PushWrapper
    id: pusht
    env:
      _target_: envs.pusht.PushTKeypointsEnv
  obs_dim: 20
  act_dim: 2
  goal_dim: ${goal_dim}
  views: 1

dataset:
  _target_: datasets.pusht.PushTDataset
  data_directory: ${env_vars.datasets.pusht}

data:
  window_size: ${window_size}
  action_window_size: ${action_window_size}
  vqbet_get_future_action_chunk: true
  goal_conditional: future
  future_seq_len: ${goal_window_size}
  min_future_sep: ${action_window_size}

save_every: 10
save_path: "${env_vars.save_path}/checkpoints/${env.gym.id}/${now:%Y-%m-%d}/${now:%H-%M-%S}"

model:
  _target_: models.vq_behavior_transformer.bet.BehaviorTransformer
  obs_dim: ${encoder.output_dim}
  act_dim: ${env.act_dim}
  goal_dim: ${env.goal_dim}
  vqvae_latent_dim: 512
  vqvae_n_embed: 16
  vqvae_groups: 2
  views: ${env.views}
  vqvae_fit_steps: 44
  vqvae_iters: 1000
  n_layer: 8
  n_head: 8
  n_embd: 512
  vqvae_batch_size: 1024
  act_scale: 500
  obs_window_size: ${window_size}
  act_window_size: ${action_window_size}
  offset_loss_multiplier: 10
