views: 1
action_dim: 9

workspace:
  _target_: workspaces.sim_kitchen.SimKitchenWorkspace

dataset:
  _target_: datasets.sim_kitchen.SimKitchenTrajectoryDataset
  data_directory: ${env_vars.datasets.sim_kitchen}
  onehot_goals: False
  prefetch: True
